language: ruby
rvm: '2.5.0'

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate

# safelist
# branches:
#   only:
#     - master
#     - ci-travis-aws
#
# deploy:
#   provider: elasticbeanstalk
#   access_key_id: 'Encrypted <access-key-id>='
#   secret_access_key:
#     secure: 'Encypted <secret-access-key>='
#   region: 'us-east-1'
#   app: 'example-app-name'
#   env: 'example-app-environment'
#   bucket_name: 'the-target-S3-bucket'
